# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('image_1', models.CharField(max_length=100)),
                ('image_2', models.CharField(max_length=100)),
                ('image_3', models.CharField(max_length=100)),
                ('image_4', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('delivery', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('pid', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'xiaomi_detail',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=40)),
                ('mid', models.IntegerField(null=True)),
                ('pay_menu', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
                ('big_title', models.CharField(max_length=10)),
                ('pay_title', models.CharField(max_length=20)),
                ('select', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('plate_id', models.IntegerField(null=True)),
                ('product_description', models.CharField(max_length=100)),
                ('big_image', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Xiaomi_index',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('pid', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'xiaomi_list',
            },
        ),
        migrations.CreateModel(
            name='Paymenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=50)),
                ('pid', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'xiaomi_PayTitle',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('cellphone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('xiaomiid', models.CharField(max_length=200, null=True)),
                ('orderformid', models.IntegerField(null=True)),
                ('collectid', models.IntegerField(null=True)),
                ('site', models.IntegerField(null=True)),
                ('portrait', models.ImageField(upload_to='file')),
                ('username', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[('0', '女'), ('1', '男')], default=0)),
            ],
            options={
                'db_table': 'mi_user',
                'managed': True,
            },
        ),
    ]
