# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platen',
            name='platename',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
