# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190823_0931'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platen',
            table='mi_platen',
        ),
    ]
